bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paperbacks_ink.urls')),
]

paperbacks_ink/urls.py
"""Defines URL patterns for paperbacks_ink."""

from django.urls import path

from . import views

app_name = 'paperbacks_ink'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Events page
    path('about/', views.events, name='events'),
    # Kaffee Kultur page
    path('kaffee/', views.kaffee, name='kaffee'),
    # Contact Us
    path('contact/', views.contact, name='contact'),

]

paperbacks_ink/models.py
from django.db import models

# Create your models here.

paperbacks_ink/views.py
from django.shortcuts import render


def index(request):
    """The home page for Paperbacks Ink."""
    return render(request, "paperbacks_ink/index.html")


def events(request):
    """Shows Events page."""
    return render(request, "paperbacks_ink/events.html")


def kaffee(request):
    """Shows Kaffee Kultur page."""
    return render(request, "paperbacks_ink/kaffee.html")


def contact(request):
    """Shows Contact Us page."""
    return render(request, "paperbacks_ink/contact.html")

paperbacks_ink/templates/paperbacks_ink/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% bootstrap_css %}
  <!-- tells Django to include all Bootstrap style files -->
  {% bootstrap_javascript jquery='full' %}
  <!-- enables all interactive behavior -->
  <title>Paperbacks Ink</title>

  <!-- Defining the navigation bar -->
</head>

<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <!-- Navigation links will be Bootstrap styled -->

    <a class="navbar-brand" href="{% url 'paperbacks_ink:index' %}">Paperbacks Ink</a>
    <!-- Project's name appears at far left of navbar and links to homepage -->

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <!-- Defines button that appears if window is too narrow -->

    <!-- All of the links to the site's pages; will collapse on narrow screens -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'paperbacks_ink:events' %}">
            Events</a>
        </li>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'paperbacks_ink:kaffee' %}">
                Kaffee Kultur</a>
            </li>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'paperbacks_ink:contact' %}">
                    Contact Us</a>
                </li>
              </ul>
            </div>

  </nav>

  <!-- Defining the main parts of the page -->
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

paperbacks_ink/templates/paperbacks_ink/contact.html
{% extends "paperbacks_ink/base.html" %}

{% block page_header %}
<div class="jumbotron" style="text-align: center;">
  <h1 class="display-4">Contact Us</h1>

  <p class="lead">We look forward to seeing you!</p>

  {% load static %}
  <img src="{% static 'store_outside.jpg' %}" style="margin: 25px auto 50px auto;"  width="700"
    height="400" class="img-fluid">

  
  <html>

  <head>
    <h2>Hours</h2>
    <h3>Sunday-Monday: Closed</h3>
    <h3>Tuesday-Saturday: 8:00 am- 5:00 pm </h3>
    &nbsp;&nbsp;

    <h2>Get in touch</h2>
    <h3>Phone: (757) 873-1211</h3>
    <h3>Email: paperbacksinkva@gmail.com</h3>
    &nbsp;&nbsp;

    <style type="text/css">
      /* Set the size of the div element that contains the map */
      #map {
        height: 400px;
        /* The height is 400 pixels */
        width: 50%;
        /* The width is the width of the web page */
        width: 50%;
        margin-left: auto;
        margin-right: auto;
      }
    </style>
    <script>
      // Initialize and add the map
      function initMap() {
        // The location of Paperbacks Ink
        const paperbacks_ink = { lat: 37.02648, lng: -76.45509 };
        // The map, centered at Paperbacks Ink
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 17,
          center: paperbacks_ink,
        });
        // The marker, positioned at Paperbacks Ink
        const marker = new google.maps.Marker({
          position: paperbacks_ink,
          map: map,
        });
      }
    </script>
  </head>

  <body>
    <!--The div element for the map -->
    <div id="map"></div>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <!-- API key has restricted use and can only be accessed from my IP address -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOmH8ZrQ47TMtJLVp_4P4hXFlvcYQzlfk&callback=initMap&libraries=&v=weekly"
      async></script>
  </body>

  &nbsp;&nbsp;
  <h3>Address: 9716 Warwick Blvd, Newport News 23601</h3>

  </html>

</div>

{% endblock page_header%}

paperbacks_ink/templates/paperbacks_ink/events.html
{% extends "paperbacks_ink/base.html" %}

{% block page_header %}
<div class="jumbotron" style="text-align: center;">
  <h1 class="display-4">Bring your friends or meet some of ours.</h1>

  <p class="lead">Come out for one of our craft nights, book signings, read alouds for children or other literary
    events!</p>

  {% load static %}
  <img src="{% static 'fairytale_day.jpg' %}" style="margin: 10px 10px 10px 10px;" width="450" height="450"
    class="img-fluid">

  {% load static %}
  <img src="{% static 'painting.jpg' %}" style="margin: 10px 10px 10px 10px;" width="450" height="450"
    class="img-fluid">

  <p class="lead">Please check <a href="https://www.facebook.com/pg/paperbacksink/events/?ref=page_internal">our
      Facebook page</a> for current
    event postings.</p>

  {% load static %}
  <img src="{% static 'author.jpg' %}" style="margin: 75px 10px 10px 10px;" width="900" height="450" class="img-fluid">
  <p>Local author <a href="https://www.christopherrussellauthor.com/">Christopher Russell</a> signing copies of Rebirth
    in 2020.</p>

  {% load static %}
  <img src="{% static 'string.jpg' %}" style="margin: 25px 10px 10px 10px;" width="500" height="500" class="img-fluid">

  {% load static %}
  <img src="{% static 'snowflakesb.jpg' %}" style="margin: 25px 10px 10px 10px;" width="500" height="600"
    class="img-fluid">

  {% load static %}
  <img src="{% static 'xmas_trees.jpg' %}" style="margin: 25px 10px 10px 10px;" width="800" height="700"
    class="img-fluid">

</div>

{% endblock page_header%}

paperbacks_ink/templates/paperbacks_ink/index.html
{% extends "paperbacks_ink/base.html" %}

<!-- Styling the home page using a jumbotron -->
{% block page_header %}
<div class="jumbotron" style="text-align: center;">
    <h1 class="display-4">If I'm ever stranded, let it be in a bookstore!</h1>
    <p class="lead">Welcome to Paperbacks Ink</p>

    {% load static %}
    <img src="{% static 'store_front.jpg' %}" style="margin: 25px 45px 10px 10px;" width="700" height="500"
      class="img-fluid">
    <!-- Load an image, define borders, define dimensions -->

    <p class="lead">Since 1982, Paperbacks Ink has been buying and trading used paperbook books in Hampton Roads.
      Don't just come in to browse our selection of over 50,000 titles that turn over daily. We also proudly brew drinks
      from
      fellow small businesses, Discover Tea and Norfolk Coffee & Tea Co. Every month we have different themed drinks, as
      well as craft
      nights and book signings with local authors. Check out <a href="https://www.facebook.com/paperbacksink/">our
        Facebook page</a>
      to see what's currently happening.</p>

    {% load static %}
    <img src="{% static 'women.jpg' %}" style="margin: 75px 10px 10px 10px;" class="img-fluid" width="450" height="450">

    {% load static %}
    <img src="{% static 'black_history.jpg' %}" style="margin: 75px 10px 10px 10px;" width="450" height="450"
      class="img-fluid">

    {% load static %}
    <img src="{% static 'childrens.jpg' %}" style="margin: 25px 10px 10px 10px;" width="450" height="400">

    {% load static %}
    <img src="{% static 'books_local.jpg' %}" style="margin: 25px 10px 10px 10px;" width="450" height="400">

    {% load static %}
    <img src="{% static 'customers.jpg' %}" style="margin: 25px 10px 10px 10px;" width="450" height="600"
      class="img-fluid">

    {% load static %}
    <img src="{% static 'books.jpg' %}" style="margin: 25px 10px 10px 10px;" width="450" height="600" class="img-fluid">

    {% load static %}
    <img src="{% static 'bernie.jpg' %}" style="margin: 25px 10px 10px 10px;" width="900" height="600"
      class="img-fluid">

    {% load static %}
    <img src="{% static 'shelves_chair.jpg' %}" style="margin: 25px 10px 25px 10px;" width="900" height="600"
      class="img-fluid">

    <h3>Trade-in books get 25% of cover price to be used as store credit towards the purchase of more books. We sell
      used
      books for 50% of cover price.</h3>

</div>

{% endblock page_header%}

paperbacks_ink/templates/paperbacks_ink/kaffee.html
{% extends "paperbacks_ink/base.html" %}

{% block page_header %}
  <div class="jumbotron" style="text-align: center;">
    <h1 class="display-4">Enjoy some tea or coffee while you browse.</h1>

    <p class="lead">We proudly serve products from our partners <a href="https://www.discoverteas.com/">Discover Teas</a> 
        and <a href="https://www.norfolkcoffeeandtea.com/">Norfolk Coffee & Tea Co.</a></p>
    
    {% load static %}
    <img src="{% static 'leprechaun.jpg' %}" style="margin: 50px 10px 10px 10px;" width="400" height="400">

    {% load static %}
    <img src="{% static 'irish_latte.jpg' %}" style="margin: 50px 10px 10px 10px;" width="400" height="400">

    <p class="lead">Check <a href="https://www.facebook.com/paperbacksink/">our Facebook page</a> for weekly
        or monthly specials.</p>

    {% load static %}
    <img src="{% static 'valentines_drink.jpg' %}" style="margin: 25px 10px 10px 10px;" width="400" height="500">

    {% load static %}
    <img src="{% static 'jamaican.jpg' %}" style="margin: 25px 10px 10px 10px;" width="400" height="500">

</div>

{% endblock page_header%}